# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Taylor Siviter
author: Taylor Siviter
domain_name: siviter.xyz
tagline: Physicist, Programmer, Student
description: >
  Physicist, Programmer, Student
url: "http://siviter.xyz" # the base hostname & protocol for your site
email: taylor@siviter.xyz
github_username:  siviter-t
linkedin_username: taylor-siviter

# Reading
safe: false
include: [".htaccess"]
exclude: []
keep_files: [".git", ".svn"]
timezone: "Europe/London"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # The subpath of your site, e.g. /blog (does not include hostname)

# Outputting
permalink: date
paginate_path: /page:num
quiet: false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_number_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
    
# Stylesheets
sass:
  style: compressed

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: page

# Plugins
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Plugin: Paginate
paginate: 5
paginate_path: /blog/page-:num/